# Generated by Django 6.0.2 on 2026-02-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('monster_type', models.CharField(max_length=80)),
                ('is_elder_dragon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('stars', models.PositiveSmallIntegerField()),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='MonsterHunterWorld.monster')),
            ],
            options={
                'unique_together': {('monster', 'kind', 'name', 'condition')},
            },
        ),
    ]
