# Generated by Django 6.0.2 on 2026-02-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monsterweakness',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='monster',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddIndex(
            model_name='monsterweakness',
            index=models.Index(fields=['monster', 'kind'], name='idx_weak_monster_kind'),
        ),
        migrations.AddIndex(
            model_name='monsterweakness',
            index=models.Index(fields=['kind', 'name'], name='idx_weak_kind_name'),
        ),
        migrations.AddConstraint(
            model_name='monsterweakness',
            constraint=models.UniqueConstraint(fields=('monster', 'kind', 'name'), name='uniq_monsterweakness_monster_kind_name'),
        ),
        migrations.AddConstraint(
            model_name='monsterweakness',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 3)), name='chk_monsterweakness_stars_1_3'),
        ),
    ]
