# Generated by Django 6.0.2 on 2026-02-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0002_alter_monsterweakness_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monsterweakness',
            name='uniq_monsterweakness_monster_kind_name',
        ),
        migrations.AddField(
            model_name='monsterweakness',
            name='condition_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='monsterweakness',
            index=models.Index(fields=['condition_key'], name='idx_weak_condition_key'),
        ),
        migrations.AddConstraint(
            model_name='monsterweakness',
            constraint=models.UniqueConstraint(fields=('monster', 'kind', 'name', 'condition_key'), name='uniq_monsterweakness_monster_kind_name_conditionkey'),
        ),
    ]
