# Generated by Django 6.0.2 on 2026-02-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0003_remove_monsterweakness_uniq_monsterweakness_monster_kind_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('weapon_type', models.CharField(max_length=50)),
                ('rarity', models.PositiveSmallIntegerField()),
                ('attack_display', models.IntegerField(default=0)),
                ('attack_raw', models.IntegerField(default=0)),
                ('element', models.CharField(blank=True, max_length=40, null=True)),
                ('element_damage', models.IntegerField(blank=True, null=True)),
                ('affinity', models.SmallIntegerField(default=0)),
                ('elderseal', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['weapon_type'], name='idx_weapon_type'), models.Index(fields=['element'], name='idx_weapon_element'), models.Index(fields=['rarity'], name='idx_weapon_rarity')],
            },
        ),
    ]
