# Generated by Django 6.0.2 on 2026-02-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0004_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('max_level', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='idx_skill_name'), models.Index(fields=['max_level'], name='idx_skill_max_level')],
            },
        ),
    ]
