# Generated by Django 6.0.2 on 2026-02-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('armor_type', models.CharField(max_length=40)),
                ('rarity', models.PositiveSmallIntegerField(default=1)),
                ('defense_base', models.PositiveSmallIntegerField(default=0)),
                ('defense_max', models.PositiveSmallIntegerField(default=0)),
                ('defense_augmented', models.PositiveSmallIntegerField(default=0)),
                ('slot_1', models.PositiveSmallIntegerField(default=0)),
                ('slot_2', models.PositiveSmallIntegerField(default=0)),
                ('slot_3', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_skills', to='MonsterHunterWorld.armor')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_armors', to='MonsterHunterWorld.skill')),
            ],
        ),
        migrations.AddField(
            model_name='armor',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='armors', through='MonsterHunterWorld.ArmorSkill', to='MonsterHunterWorld.skill'),
        ),
        migrations.AddIndex(
            model_name='armorskill',
            index=models.Index(fields=['skill', 'level'], name='idx_armorskill_skill_level'),
        ),
        migrations.AddIndex(
            model_name='armorskill',
            index=models.Index(fields=['armor'], name='idx_armorskill_armor'),
        ),
        migrations.AddConstraint(
            model_name='armorskill',
            constraint=models.UniqueConstraint(fields=('armor', 'skill'), name='uniq_armorskill_armor_skill'),
        ),
        migrations.AddConstraint(
            model_name='armorskill',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='chk_armorskill_level_gte_1'),
        ),
        migrations.AddIndex(
            model_name='armor',
            index=models.Index(fields=['armor_type'], name='idx_armor_type'),
        ),
        migrations.AddIndex(
            model_name='armor',
            index=models.Index(fields=['rarity'], name='idx_armor_rarity'),
        ),
        migrations.AddIndex(
            model_name='armor',
            index=models.Index(fields=['defense_base'], name='idx_armor_defense_base'),
        ),
    ]
