# Generated by Django 6.0.2 on 2026-02-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0006_armor_armorskill_armor_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildArmorPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('gloves', 'Gloves'), ('waist', 'Waist'), ('legs', 'Legs')], max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='armorskill',
            name='chk_armorskill_level_gte_1',
        ),
        migrations.RemoveIndex(
            model_name='armor',
            name='idx_armor_type',
        ),
        migrations.RemoveIndex(
            model_name='armor',
            name='idx_armor_rarity',
        ),
        migrations.RemoveIndex(
            model_name='armor',
            name='idx_armor_defense_base',
        ),
        migrations.RemoveIndex(
            model_name='armorskill',
            name='idx_armorskill_skill_level',
        ),
        migrations.RemoveIndex(
            model_name='armorskill',
            name='idx_armorskill_armor',
        ),
        migrations.RemoveIndex(
            model_name='monsterweakness',
            name='idx_weak_monster_kind',
        ),
        migrations.RemoveIndex(
            model_name='monsterweakness',
            name='idx_weak_kind_name',
        ),
        migrations.RemoveIndex(
            model_name='monsterweakness',
            name='idx_weak_condition_key',
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='idx_skill_name',
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='idx_skill_max_level',
        ),
        migrations.RemoveIndex(
            model_name='weapon',
            name='idx_weapon_type',
        ),
        migrations.RemoveIndex(
            model_name='weapon',
            name='idx_weapon_element',
        ),
        migrations.RemoveIndex(
            model_name='weapon',
            name='idx_weapon_rarity',
        ),
        migrations.AddField(
            model_name='build',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='MonsterHunterWorld.weapon'),
        ),
        migrations.AddField(
            model_name='buildarmorpiece',
            name='armor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_usages', to='MonsterHunterWorld.armor'),
        ),
        migrations.AddField(
            model_name='buildarmorpiece',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_pieces', to='MonsterHunterWorld.build'),
        ),
        migrations.AddConstraint(
            model_name='buildarmorpiece',
            constraint=models.UniqueConstraint(fields=('build', 'slot'), name='uniq_buildarmorpiece_build_slot'),
        ),
    ]
