# Generated by Django 6.0.2 on 2026-02-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0007_build_buildarmorpiece_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rarity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='charm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='MonsterHunterWorld.charm'),
        ),
        migrations.CreateModel(
            name='CharmSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('charm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charm_skills', to='MonsterHunterWorld.charm')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_charms', to='MonsterHunterWorld.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('charm', 'skill'), name='uniq_charmskill_charm_skill')],
            },
        ),
    ]
