# Generated by Django 6.0.2 on 2026-02-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0008_charm_build_charm_charmskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecorationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_skills', to='MonsterHunterWorld.decoration')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_decorations', to='MonsterHunterWorld.skill')),
            ],
        ),
        migrations.AddField(
            model_name='decoration',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='decorations', through='MonsterHunterWorld.DecorationSkill', to='MonsterHunterWorld.skill'),
        ),
        migrations.CreateModel(
            name='BuildDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('head', 'Head'), ('chest', 'Chest'), ('gloves', 'Gloves'), ('waist', 'Waist'), ('legs', 'Legs'), ('weapon', 'Weapon')], max_length=20)),
                ('socket_index', models.PositiveSmallIntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decorations', to='MonsterHunterWorld.build')),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_usages', to='MonsterHunterWorld.decoration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('build', 'slot', 'socket_index'), name='uniq_builddecoration_build_slot_socketindex'), models.CheckConstraint(condition=models.Q(('socket_index__gte', 1), ('socket_index__lte', 3)), name='chk_builddecoration_socket_index_1_3')],
            },
        ),
        migrations.AddConstraint(
            model_name='decorationskill',
            constraint=models.UniqueConstraint(fields=('decoration', 'skill'), name='uniq_decorationskill_decoration_skill'),
        ),
    ]
