# Generated by Django 6.0.2 on 2026-02-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0009_decoration_decorationskill_decoration_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='armor_set_bonus_external_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_set_external_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_set_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_set_rank',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
