# Generated by Django 6.0.2 on 2026-02-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0010_armor_armor_set_bonus_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetBonusRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.PositiveSmallIntegerField(default=2)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('set_bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='MonsterHunterWorld.setbonus')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_bonus_ranks', to='MonsterHunterWorld.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('set_bonus', 'pieces', 'skill'), name='uniq_setbonusrank_setbonus_pieces_skill')],
            },
        ),
    ]
