# Generated by Django 6.0.2 on 2026-02-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0011_setbonus_setbonusrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='res_dragon',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='res_fire',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='res_ice',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='res_thunder',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armor',
            name='res_water',
            field=models.SmallIntegerField(default=0),
        ),
    ]
