# Generated by Django 6.0.2 on 2026-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0012_armor_res_dragon_armor_res_fire_armor_res_ice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='primary_ailment',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='primary_element',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
