# Generated by Django 6.0.2 on 2026-02-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0013_monster_primary_ailment_monster_primary_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=40)),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('condition_key', models.CharField(blank=True, default='', max_length=200)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistances', to='MonsterHunterWorld.monster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('monster', 'element', 'condition_key'), name='uniq_monsterresistance_monster_element_conditionkey')],
            },
        ),
    ]
