# Generated by Django 6.0.2 on 2026-02-22 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0014_monsterresistance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='in_inventory_of',
            field=models.ManyToManyField(blank=True, related_name='armor_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='build',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charm',
            name='in_inventory_of',
            field=models.ManyToManyField(blank=True, related_name='charm_inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weapon',
            name='in_inventory_of',
            field=models.ManyToManyField(blank=True, related_name='weapon_inventory', to=settings.AUTH_USER_MODEL),
        ),
    ]
