# Generated by Django 6.0.2 on 2026-02-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonsterHunterWorld', '0015_armor_in_inventory_of_build_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='in_inventory_of',
        ),
        migrations.RemoveField(
            model_name='build',
            name='user',
        ),
        migrations.RemoveField(
            model_name='charm',
            name='in_inventory_of',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='in_inventory_of',
        ),
    ]
