# Generated by Django 6.0.2 on 2026-02-26 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MonsterHunterWorld', '0016_remove_armor_in_inventory_of_remove_build_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('armor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonsterHunterWorld.armor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'armor'), name='uniq_armor_inventory_user_armor')],
            },
        ),
        migrations.CreateModel(
            name='CharmInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('charm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonsterHunterWorld.charm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charm_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'charm'), name='uniq_charm_inventory_user_charm')],
            },
        ),
        migrations.CreateModel(
            name='DecorationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonsterHunterWorld.decoration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'decoration'), name='uniq_decoration_inventory_user_decoration')],
            },
        ),
        migrations.CreateModel(
            name='WeaponInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_inventory', to=settings.AUTH_USER_MODEL)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonsterHunterWorld.weapon')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'weapon'), name='uniq_weapon_inventory_user_weapon')],
            },
        ),
    ]
