# Generated by Django 6.0.2 on 2026-02-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorationinventory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
