# Generated by Django 6.0.2 on 2026-03-10 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MonsterHunterWorld', '0016_remove_armor_in_inventory_of_remove_build_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_arms', to='MonsterHunterWorld.armor')),
                ('charm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MonsterHunterWorld.charm')),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_chest', to='MonsterHunterWorld.armor')),
                ('decorations', models.ManyToManyField(blank=True, to='MonsterHunterWorld.decoration')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_head', to='MonsterHunterWorld.armor')),
                ('legs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_legs', to='MonsterHunterWorld.armor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_builds', to=settings.AUTH_USER_MODEL)),
                ('waist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_waist', to='MonsterHunterWorld.armor')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MonsterHunterWorld.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='BuildComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='builds.savedbuild')),
            ],
        ),
        migrations.CreateModel(
            name='BuildLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='builds.savedbuild')),
            ],
            options={
                'unique_together': {('user', 'build')},
            },
        ),
    ]
