# Generated by Django 6.0.2 on 2026-03-03 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MonsterHunterWorld', '0016_remove_armor_in_inventory_of_remove_build_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlayedMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slayed_at', models.DateTimeField(auto_now_add=True)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonsterHunterWorld.monster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slayed_monsters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'monster'), name='uniq_slayed_monster_user_monster')],
            },
        ),
    ]
